quarkus:
  application:
    name: nexus-console
  http:
    port: 8081
  log:
    level: INFO
    category:
      "com.innospots.nexus":
        level: INFO
      "org.apache.ibatis":
        level: INFO
      "com.baomidou.mybatisplus":
        level: INFO
      "io.quarkus":
        level: INFO
    console:
      enable: true
      format: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5p [%c{2.}] (%t) %s%e%n"
    file:
      enable: true
      path: logs/nexus-console.log
      format: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5p [%c{2.}] (%t) %s%e%n"
      rotation:
        max-file-size: 100M
        max-backup-index: 100
  datasource:
    db-kind: h2
    username: sa
    password: ""
    jdbc:
      url: jdbc:h2:mem:nexus-console;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1
    devservices:
      enabled: false
  index-dependency:
    nexus-core:
      group-id: com.innospots
      artifact-id: innospots-nexus-core
  mybatis:
    initial-sql: nexus/schema/plugin-installation-h2.sql,nexus/schema/console-catalog-h2.sql
    map-underscore-to-camel-case: true
  mybatis-plus:
    global-config:
      meta-object-handler: com.innospots.nexus.core.persistence.handler.AuditMetaObjectHandler
      db-config:
        id-type: ASSIGN_UUID

nexus:
  workspace:
    default-id: default
  plugins:
    required:
      - com.innospots.nexus.console.menu
      - com.innospots.nexus.console.dictionary
      - com.innospots.nexus.console.logger
      - com.innospots.nexus.console.permission
      - com.innospots.nexus.console.role
      - com.innospots.nexus.console.plugin-management

# nexus.plugin.* / plugins.* 配置方式同 innospots-nexus-quarkus-app
