# 租户控制台服务：控制台认证与凭据（innospots-nexus-spring-console）
#
# 绑定: com.innospots.nexus.spring.console.config.ConsoleAuthProperties
#       com.innospots.nexus.spring.console.config.ConsoleCredentialTotpProperties
# 装配: ConsoleAuthConfiguration, ConsoleCredentialConfiguration, KernelAuthConfiguration
#
nexus:
  console:
    auth:
      token-secret: "0123456789abcdef"
      access-token-ttl-seconds: 7200
      refresh-token-ttl-seconds: 604800
      tenant-login-captcha-enabled: false
      platform-login-captcha-enabled: true
      login-max-failed-attempts: 5
      login-lock-minutes: 15
      rsa:
        private-key: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCtwgwE8LlWbM8Cis4wr9HA6F/s7OYN/mjGIGGurviLTXzQEoJzPu3U+G6XeMwzWzRBX82Aizf5eQKg6I2ytP4VtpkMtcq6wjztks1pqBpBCwfdKrrjp08DpugTlV8bSjgNoyI7Dzu4cmavRotY3u6wHv2rUKmnOEoWisQ4H2y4FjKq3ZCHGHVv31SoUSI82vFmb3T+WOV/1nsmiS/QFA/PbWtXIQUxbmmfBoXOr/01MhCb5QmKcQFobjQ49H2a7S2yawdUICb3BRtuq3n+hErsoKfPeMqjlepBborfy0c2MaHw1tXrxMw1MvuTS/CWwiTffXn+bIRA+AhRJpm3O7PvAgMBAAECggEACbUQPCvBWaAKkKHLPdJqGCo4nGE/w621khwNA61SxWA224kChghl+8KaqxZckiHuRsNgv7sHYttCglV7qm2Mzw8Rzdv6JM+P3StDvpCy/B9ETomB7LtUIWgZtGkL6de4+fS7MiwlB1DyMP3ymwHEDqLXQ9Ll0inFjyzWztaH7wt23PO64MJNVFHQ/BhRLYqwDdQj+p7wvPAG0y5PHKL0Y4DexM9aUhK3rOxaHQ8yZt8bHl40iXU18yKr2KKbU+rRj6QVoMpMSpM1ZEP6vXC6rFPHqPFi/uxdS9cdWnMlgzx3VD1oc51HRxxuvTCZ2yqbunURncJs7I5IFAOIt9APgQKBgQDWNhkjReHWKaJsip4EGy391OLH8GzOBzKv8c7u22h+MqwEiUTw+Gd01848bd23p9EMl9chU6t0Ab0WEvMsChk49VU1J+lHj1WRZkWo6oYRaAaZHaCDbstor+PfXspXA8HaPA3jWretoEBcsK2f+z9AkddTxyeJ/X4TWuGjjRRohwKBgQDPp6ySmri2rWf6uI0V5A/wjJhL0ACNmQd4MlFOjByskcKMQcdBzdZbKoESFuT0ZNAwYb9kycLMBnBNpjTgHnmz3hDKj2mbAkpMKsuwiTdFeGdvsWYUeCUzPnK4cj0qTAdfnbTbAIW9IgULGdrK1/uarE+5ISv94J5dNxbDZuH7WQKBgFLQvW02ojYDCKl/+dFKlMBSoo579AS/IaiGCuOrbb2EZ56lV0L2NkElAbW5IAPV3GtK9MAMsfd6iJjVILBBAzlTF+siD/07e/BnorzIVqa6GfruSlUl63wArE96PS3g5PwzRYdFVkfI8bkkESwNnYmgGKhqEW4205w2AZAShfZXAoGAK1X1yN6rP8xuj79mCjR/MxdUTTYKd4KBMY9msnrBHS6KKFUt7Ui0vG/hYdIPVAWaAQ7VL4Z/ta5+T2YpUMBra6MjY/KL+oJ+2Ohxe9UXCNN42rFt+UWdldUpgd6tbx9Qxp6V+MJiJrdr0AZER+LNKlldhegrUx9GTXPKt1rIPHkCgYAYGGQohTYiH/++n5iqALeZ7Rbtq4wM7ikGiqGWuQnoqPj8yoeA6rPAZfNIceNj4zh5+r1NjrczE+A5U1XkF+RlKVaH3rKRvNplyRBaqW2K4rJOm/zIGpZs/4UoNYSMDA1qIhiG+Z8B55ygoQcztb2dvFBPicNrYkTwaPNCpWtONQ==
    credential:
      totp:
        # master-key: "change-me-in-production"
