<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.innospots</groupId>
        <artifactId>innospots-nexus-quarkus</artifactId>
        <version>${revision}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>innospots-nexus-quarkus-portal</artifactId>
    <packaging>jar</packaging>

    <name>innospots-nexus-quarkus-portal</name>
    <description>innospots-nexus portal 业务域 Quarkus 装配库（依赖 quarkus-console，不含 platform）。</description>

    <dependencies>
        <dependency>
            <groupId>com.innospots</groupId>
            <artifactId>innospots-nexus-quarkus-console</artifactId>
        </dependency>
        <dependency>
            <groupId>com.innospots</groupId>
            <artifactId>innospots-nexus-portal</artifactId>
        </dependency>
    </dependencies>
</project>
