-- MySQL DDL for innospots-nexus-console entities.
-- IDs are application assigned; inherited audit and ownership columns are expanded per entity.

CREATE TABLE IF NOT EXISTS nx_console_catalog_resource (
    resource_id          VARCHAR(32)  NOT NULL,
    owner_plugin_id      VARCHAR(256) NOT NULL,
    module_key           VARCHAR(128) NOT NULL,
    resource_type        VARCHAR(32)  NOT NULL,
    resource_key         VARCHAR(256) NOT NULL,
    parent_resource_id   VARCHAR(32),
    page_key             VARCHAR(256),
    datasource_key       VARCHAR(128),
    route_path           VARCHAR(512),
    request_method       VARCHAR(16),
    request_url          VARCHAR(512),
    display_name         VARCHAR(256),
    sort_order           INT          NOT NULL,
    status               VARCHAR(32)  NOT NULL,
    security_realm       VARCHAR(32)  NOT NULL,
    created_at           DATETIME(6),
    updated_at           DATETIME(6),
    created_by           VARCHAR(64),
    updated_by           VARCHAR(64),
    PRIMARY KEY (resource_id),
    CONSTRAINT uk_nx_console_catalog_resource_key UNIQUE (resource_key),
    KEY idx_nx_console_catalog_resource_source (owner_plugin_id, module_key, resource_type, status),
    KEY idx_nx_console_catalog_resource_parent (parent_resource_id, sort_order),
    KEY idx_nx_console_catalog_resource_request (page_key, request_method, request_url(384)),
    KEY idx_nx_console_catalog_resource_realm (security_realm)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS nx_otp_challenge (
    challenge_id    VARCHAR(32)  NOT NULL,
    purpose         VARCHAR(32)  NOT NULL,
    channel         VARCHAR(32)  NOT NULL,
    destination     VARCHAR(256) NOT NULL,
    algorithm       VARCHAR(64)  NOT NULL,
    code_verifier   VARCHAR(512) NOT NULL,
    expires_at      DATETIME(6)  NOT NULL,
    consumed_at     DATETIME(6),
    attempt_count   INT          NOT NULL,
    max_attempts    INT          NOT NULL,
    resend_count    INT          NOT NULL,
    owner_type      VARCHAR(32)  NOT NULL,
    owner_id        VARCHAR(32),
    security_realm  VARCHAR(32)  NOT NULL,
    created_at      DATETIME(6),
    updated_at      DATETIME(6),
    created_by      VARCHAR(64),
    updated_by      VARCHAR(64),
    PRIMARY KEY (challenge_id),
    KEY idx_nx_otp_challenge_lookup (owner_type, owner_id, security_realm, purpose, channel, destination),
    KEY idx_nx_otp_challenge_expires (expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS nx_user_credential (
    credential_id       VARCHAR(32)   NOT NULL,
    subject_id          VARCHAR(32)   NOT NULL,
    credential_kind     VARCHAR(32)   NOT NULL,
    algorithm           VARCHAR(64)   NOT NULL,
    verifier            VARCHAR(512)  NOT NULL,
    verifier_params     VARCHAR(1024),
    credential_version  INT           NOT NULL,
    force_reset         TINYINT(1)    NOT NULL,
    failed_attempts     INT           NOT NULL,
    locked_until        DATETIME(6),
    expired_at          DATETIME(6),
    owner_type          VARCHAR(32)   NOT NULL,
    owner_id            VARCHAR(32),
    security_realm      VARCHAR(32)   NOT NULL,
    created_at          DATETIME(6),
    updated_at          DATETIME(6),
    created_by          VARCHAR(64),
    updated_by          VARCHAR(64),
    PRIMARY KEY (credential_id),
    CONSTRAINT uk_nx_user_credential_subject UNIQUE (owner_type, owner_id, security_realm, credential_kind, subject_id),
    KEY idx_nx_user_credential_subject (subject_id, credential_kind)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS nx_dictionary_item (
    dictionary_item_id  VARCHAR(32)  NOT NULL,
    type_code           VARCHAR(64)  NOT NULL,
    item_value          VARCHAR(64)  NOT NULL,
    item_name           VARCHAR(128) NOT NULL,
    status              VARCHAR(32)  NOT NULL,
    sort_order          INT          NOT NULL,
    built_in            TINYINT(1)   NOT NULL,
    owner_type          VARCHAR(32)  NOT NULL,
    owner_id            VARCHAR(32),
    security_realm      VARCHAR(32)  NOT NULL,
    created_at          DATETIME(6),
    updated_at          DATETIME(6),
    created_by          VARCHAR(64),
    updated_by          VARCHAR(64),
    PRIMARY KEY (dictionary_item_id),
    CONSTRAINT uk_nx_dictionary_item_value UNIQUE (owner_type, owner_id, security_realm, type_code, item_value),
    KEY idx_nx_dictionary_item_type (owner_type, owner_id, type_code, sort_order),
    KEY idx_nx_dictionary_item_realm (security_realm)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS nx_dictionary_type (
    dictionary_type_id  VARCHAR(32)  NOT NULL,
    type_code           VARCHAR(64)  NOT NULL,
    type_name           VARCHAR(128) NOT NULL,
    status              VARCHAR(32)  NOT NULL,
    sort_order          INT          NOT NULL,
    built_in            TINYINT(1)   NOT NULL,
    owner_type          VARCHAR(32)  NOT NULL,
    owner_id            VARCHAR(32),
    security_realm      VARCHAR(32)  NOT NULL,
    created_at          DATETIME(6),
    updated_at          DATETIME(6),
    created_by          VARCHAR(64),
    updated_by          VARCHAR(64),
    PRIMARY KEY (dictionary_type_id),
    CONSTRAINT uk_nx_dictionary_type_code UNIQUE (owner_type, owner_id, security_realm, type_code),
    KEY idx_nx_dictionary_type_status (owner_type, owner_id, status),
    KEY idx_nx_dictionary_type_realm (security_realm)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS nx_audit_log (
    audit_log_id     VARCHAR(32)   NOT NULL,
    action           VARCHAR(64)   NOT NULL,
    path             VARCHAR(256)  NOT NULL,
    operated_time    DATETIME(6)   NOT NULL,
    actor            VARCHAR(64),
    message          VARCHAR(512),
    status_code      VARCHAR(32),
    execution_result VARCHAR(32)   NOT NULL,
    key_parameters   VARCHAR(2048),
    owner_type       VARCHAR(32)   NOT NULL,
    owner_id         VARCHAR(32),
    security_realm   VARCHAR(32)   NOT NULL,
    created_at       DATETIME(6),
    updated_at       DATETIME(6),
    created_by       VARCHAR(64),
    updated_by       VARCHAR(64),
    PRIMARY KEY (audit_log_id),
    KEY idx_nx_audit_log_time (operated_time),
    KEY idx_nx_audit_log_action (action),
    KEY idx_nx_audit_log_actor (actor),
    KEY idx_nx_audit_log_result (execution_result),
    KEY idx_nx_audit_log_owner_time (owner_type, owner_id, operated_time),
    KEY idx_nx_audit_log_realm_time (security_realm, operated_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS nx_menu (
    menu_id         VARCHAR(32)  NOT NULL,
    parent_id       VARCHAR(32),
    menu_key        VARCHAR(64)  NOT NULL,
    menu_name       VARCHAR(128) NOT NULL,
    menu_type       VARCHAR(32)  NOT NULL,
    route_path      VARCHAR(256),
    component_key   VARCHAR(128),
    redirect_path   VARCHAR(256),
    external_url    VARCHAR(512),
    icon            VARCHAR(128),
    open_mode       VARCHAR(32)  NOT NULL,
    visible         TINYINT(1)   NOT NULL,
    status          VARCHAR(32)  NOT NULL,
    sort_order      INT          NOT NULL,
    built_in        TINYINT(1)   NOT NULL,
    owner_type      VARCHAR(32)  NOT NULL,
    owner_id        VARCHAR(32),
    security_realm  VARCHAR(32)  NOT NULL,
    created_at      DATETIME(6),
    updated_at      DATETIME(6),
    created_by      VARCHAR(64),
    updated_by      VARCHAR(64),
    PRIMARY KEY (menu_id),
    CONSTRAINT uk_nx_menu_owner_key UNIQUE (owner_type, owner_id, security_realm, menu_key),
    KEY idx_nx_menu_owner_parent_order (owner_type, owner_id, parent_id, sort_order),
    KEY idx_nx_menu_owner_status_visible (owner_type, owner_id, status, visible),
    KEY idx_nx_menu_realm (security_realm)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS nx_permission_grant (
    grant_id               VARCHAR(32) NOT NULL,
    subject_type           VARCHAR(32) NOT NULL,
    subject_id             VARCHAR(32) NOT NULL,
    resource_id            VARCHAR(32) NOT NULL,
    constraint_definition  TEXT,
    owner_type             VARCHAR(32) NOT NULL,
    owner_id               VARCHAR(32),
    security_realm         VARCHAR(32) NOT NULL,
    created_at             DATETIME(6),
    updated_at             DATETIME(6),
    created_by             VARCHAR(64),
    updated_by             VARCHAR(64),
    PRIMARY KEY (grant_id),
    CONSTRAINT uk_nx_permission_grant_subject_resource UNIQUE (owner_type, owner_id, security_realm, subject_type, subject_id, resource_id),
    KEY idx_nx_permission_grant_subject (owner_type, owner_id, subject_type, subject_id),
    KEY idx_nx_permission_grant_resource (owner_type, owner_id, resource_id),
    KEY idx_nx_permission_grant_realm (security_realm)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS nx_role_binding (
    binding_id    VARCHAR(32) NOT NULL,
    role_id       VARCHAR(32) NOT NULL,
    subject_type  VARCHAR(32) NOT NULL,
    subject_id    VARCHAR(32) NOT NULL,
    owner_type    VARCHAR(32) NOT NULL,
    owner_id      VARCHAR(32),
    security_realm VARCHAR(32) NOT NULL,
    created_at    DATETIME(6),
    updated_at    DATETIME(6),
    created_by    VARCHAR(64),
    updated_by    VARCHAR(64),
    PRIMARY KEY (binding_id),
    CONSTRAINT uk_nx_role_binding_subject UNIQUE (owner_type, owner_id, security_realm, role_id, subject_type, subject_id),
    KEY idx_nx_role_binding_subject (subject_type, subject_id),
    KEY idx_nx_role_binding_role (role_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS nx_role (
    role_id         VARCHAR(32)  NOT NULL,
    role_name       VARCHAR(64)  NOT NULL,
    role_code       VARCHAR(64)  NOT NULL,
    owner_type      VARCHAR(32)  NOT NULL,
    owner_id        VARCHAR(32),
    security_realm  VARCHAR(32)  NOT NULL,
    description     VARCHAR(256),
    status          VARCHAR(32)  NOT NULL,
    sort_order      INT          NOT NULL,
    built_in        TINYINT(1)   NOT NULL,
    administrator   TINYINT(1)   NOT NULL,
    created_at      DATETIME(6),
    updated_at      DATETIME(6),
    created_by      VARCHAR(64),
    updated_by      VARCHAR(64),
    PRIMARY KEY (role_id),
    CONSTRAINT uk_nx_role_owner_code UNIQUE (owner_type, owner_id, security_realm, role_code),
    KEY idx_nx_role_owner_status (owner_type, owner_id, status),
    KEY idx_nx_role_name (role_name),
    KEY idx_nx_role_realm (security_realm)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
